trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: gitee_event
      type: STRING
      exp: $.header.X-Gitee-Event
    - name: git_ref
      type: STRING
      exp: $.body.json.ref
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  matcher: (${trigger.gitee_event} == "Push Hook" && ${trigger.git_ref} == "refs/heads/test")

pipeline:
  name: 批量导入项目
  git_clone:
    type: git_clone:1.1.1
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-ci-dsl.git
      ref: refs/heads/test
      netrc_machine: gitee.com
      netrc_username: ((gitee.username))
      netrc_password: ((gitee.password))
  reconfigure_project:
    type: sync_project_group:1.0.0
    param:
      ci_url: https://ci.test.jianmu.dev
      ci_username: ((jianmu_ci.username))
      ci_password: ((jianmu_ci.password))
      git_path: ${git_clone.git_path}
      group_file_path: /project_group.yml
      deletable: false
