projects:
  # 建木api网关
  - config_file: /api-gw/cicd.yml
  # 建木ci
  - config_file: /ci/server_cicd.yml
  - config_file: /ci/ui_cicd.yml
  # 开发工具
  - config_file: /dev-tools/docker_image_builder.yml
  # 建木hub
  - config_file: /hub/server_cicd.yml
  - config_file: /hub/ui_cicd.yml
  # 官网
  - config_file: /official-site/web_cicd.yml
  - config_file: /official-site/wap_cicd.yml
