name: 更新ssl证书：*.internal.jianmu.dev

global:
  param:
    domain: "*.internal.jianmu.dev"
    ssl_dir_nexus: /home/ubuntu/ssl/_.internal.jianmu.dev
    ssl_dir_internal_env: /home/ubuntu/ssl/_.internal.jianmu.dev

trigger:
  type: cron
  schedule: 0 0 12 5 * ? *

workflow:
  start:
    type: start
    targets:
      - acme_ssl_aliyun
  acme_ssl_aliyun:
    sources:
      - start
    targets:
      - scp_cert_nexus
      - scp_key_nexus
      - scp_cert_internal_env
      - scp_key_internal_env
    type: acme_ssl_aliyun:1.0.1
    param:
      wget_use: true
      ali_key: ((ali.jianmu_dev_key))
      domain: ${global.domain}
      ali_secret: ((ali.jianmu_dev_secret))
      dns_check: true
      email: dev@jianmu.dev
  scp_cert_nexus:
    sources:
      - acme_ssl_aliyun
    targets:
      - restart_nginx_nexus
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.16.101.232
      ssh_user: ubuntu
      ssh_private_key: ((private_key.232))
      remote_file: ${global.ssl_dir_nexus}/fullchain.cer
      local_file: ${acme_ssl_aliyun.cer_path}
  scp_key_nexus:
    sources:
      - acme_ssl_aliyun
    targets:
      - restart_nginx_nexus
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.16.101.232
      ssh_user: ubuntu
      ssh_private_key: ((private_key.232))
      remote_file: ${global.ssl_dir_nexus}/private.key
      local_file: ${acme_ssl_aliyun.key_path}
  restart_nginx_nexus:
    sources:
      - scp_cert_nexus
      - scp_key_nexus
    targets:
      - send_message
      - send_email
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 172.16.101.232
      ssh_user: ubuntu
      ssh_private_key: ((private_key.232))
      ssh_cmd: sudo systemctl restart nginx
  scp_cert_internal_env:
    sources:
      - acme_ssl_aliyun
    targets:
      - restart_nginx_internal_env
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.16.101.254
      ssh_user: ubuntu
      ssh_private_key: ((private_key.254))
      remote_file: ${global.ssl_dir_internal_env}/fullchain.cer
      local_file: ${acme_ssl_aliyun.cer_path}
  scp_key_internal_env:
    sources:
      - acme_ssl_aliyun
    targets:
      - restart_nginx_internal_env
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.16.101.254
      ssh_user: ubuntu
      ssh_private_key: ((private_key.254))
      remote_file: ${global.ssl_dir_internal_env}/private.key
      local_file: ${acme_ssl_aliyun.key_path}
  restart_nginx_internal_env:
    sources:
      - scp_cert_internal_env
      - scp_key_internal_env
    targets:
      - send_message
      - send_email
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 172.16.101.254
      ssh_user: ubuntu
      ssh_private_key: ((private_key.254))
      ssh_cmd: sudo systemctl restart nginx
  send_message:
    sources:
      - restart_nginx_nexus
      - restart_nginx_internal_env
    targets:
      - end
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      msg_title: 更新ssl证书（${global.domain}）更新完成。
      msg_text: ""
  send_email:
    sources:
      - restart_nginx_nexus
      - restart_nginx_internal_env
    targets:
      - end
    type: email:1.0.0
    param:
      host: smtp.ym.163.com
      sender: notice@jianmu.dev
      auth_code: ((email.notice_auth_code))
      receivers: '["dev@jianmu.dev"]'
      type: html
      subject: ssl证书更新完成:（${global.domain}）
      text: ssl证书（${global.domain}）更新完成。
  end:
    type: end
    sources:
      - send_email
      - send_message
