name: 更新ssl证书：*.test.jianmu.dev

global:
  param:
    domain: "*.test.jianmu.dev"
    ssl_dir: /etc/nginx/ssl/_.test.jianmu.dev
    ssl_dir_test_env: /home/ubuntu/ssl/_.test.jianmu.dev

trigger:
  type: cron
  schedule: 0 0 12 3 * ? *

workflow:
  start:
    type: start
    targets:
      - acme_ssl_aliyun
  acme_ssl_aliyun:
    sources:
      - start
    targets:
      - scp_cert_inner
      - scp_key_inner
      - scp_cert_test_env
      - scp_key_test_env
    type: acme_ssl_aliyun:1.0.1
    param:
      wget_use: true
      ali_key: ((ali.jianmu_dev_key))
      domain: ${global.domain}
      ali_secret: ((ali.jianmu_dev_secret))
      dns_check: true
      email: dev@jianmu.dev
  scp_cert_inner:
    sources:
      - acme_ssl_aliyun
    targets:
      - ssh_cmd_inner
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.20.151.88
      ssh_private_key: ((private_key.test_hub))
      remote_file: ${global.ssl_dir}/fullchain.cer
      local_file: ${acme_ssl_aliyun.cer_path}
  scp_key_inner:
    sources:
      - acme_ssl_aliyun
    targets:
      - ssh_cmd_inner
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.20.151.88
      ssh_private_key: ((private_key.test_hub))
      remote_file: ${global.ssl_dir}/private.key
      local_file: ${acme_ssl_aliyun.key_path}
  ssh_cmd_inner:
    sources:
      - scp_cert_inner
      - scp_key_inner
    targets:
      - send_message
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 172.20.151.88
      ssh_private_key: ((private_key.test_hub))
      ssh_cmd: systemctl restart nginx
  scp_cert_test_env:
    sources:
      - acme_ssl_aliyun
    targets:
      - restart_nginx_test_env
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.16.101.253
      ssh_user: ubuntu
      ssh_private_key: ((private_key.253))
      remote_file: ${global.ssl_dir_test_env}/fullchain.cer
      local_file: ${acme_ssl_aliyun.cer_path}
  scp_key_test_env:
    sources:
      - acme_ssl_aliyun
    targets:
      - restart_nginx_test_env
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.16.101.253
      ssh_user: ubuntu
      ssh_private_key: ((private_key.253))
      remote_file: ${global.ssl_dir_test_env}/private.key
      local_file: ${acme_ssl_aliyun.key_path}
  restart_nginx_test_env:
    sources:
      - scp_cert_test_env
      - scp_key_test_env
    targets:
      - send_message
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 172.16.101.253
      ssh_user: ubuntu
      ssh_private_key: ((private_key.253))
      ssh_cmd: sudo systemctl restart nginx
  send_message:
    sources:
      - ssh_cmd_inner
      - restart_nginx_test_env
    targets:
      - send_email
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      msg_title: 更新ssl证书（${global.domain}）更新完成。
      msg_text: ""
  send_email:
    sources:
      - send_message
    targets:
      - end
    type: email:1.0.0
    param:
      host: smtp.ym.163.com
      sender: notice@jianmu.dev
      auth_code: ((email.notice_auth_code))
      receivers: '["dev@jianmu.dev"]'
      type: html
      subject: ssl证书更新完成:（${global.domain}）
      text: ssl证书（${global.domain}）更新完成。
  end:
    type: end
    sources:
      - send_email
