name: 更新ssl证书：*.internal.jianmuhub.com

global:
  param:
    domain: "*.internal.jianmuhub.com"
    ssl_dir: /home/ubuntu/ssl/_.internal.jianmuhub.com

trigger:
  type: cron
  schedule: 0 0 12 22 * ? *

workflow:
  start:
    type: start
    targets:
      - acme_ssl_aliyun
  acme_ssl_aliyun:
    sources:
      - start
    targets:
      - scp_cert
      - scp_key
    type: acme_ssl_aliyun:1.0.1
    param:
      wget_use: true
      ali_key: ((ali.jianmuhub_com_key))
      domain: ${global.domain}
      ali_secret: ((ali.jianmuhub_com_secret))
      dns_check: true
      email: dev@jianmu.dev
  scp_cert:
    sources:
      - acme_ssl_aliyun
    targets:
      - ssh_cmd
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.16.101.254
      ssh_user: ubuntu
      ssh_private_key: ((private_key.254))
      remote_file: ${global.ssl_dir}/fullchain.cer
      local_file: ${acme_ssl_aliyun.cer_path}
  scp_key:
    sources:
      - acme_ssl_aliyun
    targets:
      - ssh_cmd
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.16.101.254
      ssh_user: ubuntu
      ssh_private_key: ((private_key.254))
      remote_file: ${global.ssl_dir}/private.key
      local_file: ${acme_ssl_aliyun.key_path}
  ssh_cmd:
    sources:
      - scp_cert
      - scp_key
    targets:
      - send_message
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 172.16.101.254
      ssh_user: ubuntu
      ssh_private_key: ((private_key.254))
      ssh_cmd: sudo systemctl restart nginx
  send_message:
    sources:
      - ssh_cmd
    targets:
      - end
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      msg_title: 更新ssl证书（${global.domain}）更新完成。
      msg_text: ""
  end:
    type: end
    sources:
      - send_message
