name: 更新ssl证书：cdn.test.dghub.cn
description: 更新ssl证书：cdn.test.dghub.cn
global:
  param:
    domain: "cdn.test.dghub.cn"

trigger:
  type: cron
  schedule: 0 0 12 18 * ? *

pipeline:
  acme_ssl_aliyun:
    type: "acme_ssl_aliyun:1.0.2"
    param:
      wget_use: true
      ali_key: ((ali.dghub_cn_key))
      domain: ${global.domain}
      ali_secret: ((ali.dghub_cn_secret))
      # 调试时为false
      dns_check: true
      email: dev@jianmu.dev
  qiniu_ssl_upload:
    type: "qiniu:1.0.0-ssl-upload"
    param:
      certificate_path: ${acme_ssl_aliyun.cer_path}
      certificate_key_path: ${acme_ssl_aliyun.key_path}
      domain: ${global.domain}
      # 七牛云密钥管理中的AK
      qiniu_access_key: ((qiniu.AccessKey))
      # 七牛云密钥管理中的SK
      qiniu_secret_key: ((qiniu.SecretKey))
  domain_ssl_update:
    type: "qiniu:1.0.0-domain-ssl-update"
    param:
      domain: ${global.domain}
      access_key: ((qiniu.AccessKey))
      secret_key: ((qiniu.SecretKey))
      cert_id: ${qiniu_ssl_upload.cert_id}
      force_https: true
      http2_enable: true
  feishu_notice:
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      msg_title: 七牛云ssl证书（${global.domain}）更新完成。
      msg_text: ""
  send_email:
    type: email:1.0.0
    param:
      host: smtp.ym.163.com
      sender: notice@jianmu.dev
      auth_code: ((email.notice_auth_code))
      receivers: '["dev@jianmu.dev"]'
      type: html
      subject: 七牛云ssl证书更新完成:（${global.domain}）
      text: 七牛云ssl证书（${global.domain}）更新完成。