name: 构建贡献者列表
description: 构建贡献者列表

trigger:
  type: webhook
  param:
    - name: username
      type: STRING
      exp: $.body.json.pull_request.user.login
    - name: nickname
      type: STRING
      exp: $.body.json.pull_request.user.name
    - name:  avatar_url
      type: STRING
      exp: $.body.json.pull_request.user.avatar_url
    - name: action
      type: STRING
      exp: $.body.json.action
    - name: pr_url
      type: STRING
      exp: $.body.json.url
    - name: email
      type: STRING
      exp: $.body.json.pull_request.user.email
    - name: org_name
      type: STRING
      exp: $.body.json.project.namespace
  only: (${trigger.action} === "merge")

workflow:
  start:
    type: start
    targets:
      - git_clone
  git_clone:
    type: git_clone:1.2.0
    sources:
      - start
    targets:
      - contributors
    param:
      remote_url: https://gitee.com/green-grassland-hx/governance.git
  contributors:
    type: contributors_build:1.0.0-gitee
    sources:
      - git_clone
    targets:
      - git_push
      - sync_contributors_jsonfile
    param:
      json_filepath: ${git_clone.git_path}/data/contributors.json
      username: ${trigger.username}
      nickname: ${trigger.nickname}
      avatar_url: ${trigger.avatar_url}
      pr_url: ${trigger.pr_url}
      email: ${trigger.email}
  git_push:
    type: git_push:1.0.2
    sources:
      - contributors
    targets:
      - member_add
    param:
      ssh_key: ((gitee.huangxi_key))
      remote_url: git@gitee.com:green-grassland-hx/governance.git
      source_path: ${contributors.contributors_json_filepath}
      target_dir: governance/data
      commit_message: "refactor: contributors.json"
  sync_contributors_jsonfile:
    sources:
      - contributors
    targets:
      - member_add
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.20.148.144
      ssh_private_key: ((144key.ssh_rsa))
      remote_file: /tmp/hx/json/contributors.json
      local_file: ${contributors.contributors_json_filepath}
  member_add:
    sources:
      - git_push
      - sync_contributors_jsonfile
    targets:
      - send_message
    type: gitee:1.0.0-member-add
    param:
      access_token: ((gitee.huangxi_token))
      org: ${trigger.org_name}
      username: ${trigger.username}
  send_message:
    sources:
      - member_add
    targets:
      - end
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      msg_title: 贡献者已加入
      msg_text: "昵称：${trigger.nickname}\n用户名：${trigger.username}"
  end:
    type: end
    sources:
      - send_message

