# 部署生产，通过上游打镜像流程，触发（结合chat-ops）
name: 建木CLA前端CDN CD
description: 建木CLA前端CDN CD

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-dev/opencla.git
      ref: refs/tags/v0.0.11
      username: ((gitee.username))
      password: ((gitee.password))
  node_build:
    type: nodejs_build:1.2.1-16.13.0
    param:
      workspace: ${git_clone.git_path}/ui
      registry_url: https://registry.npm.taobao.org
      build_arg: --mode cdn
  qiniu_upload:
    type: qiniu:1.0.0-file-upload
    param:
      qiniu_bucket: jianmu
      qiniu_ak: ((qiniu.AccessKey))
      qiniu_sk: ((qiniu.SecretKey))
      qiniu_zone: z1
      qiniu_upload_uri_prefix: ${node_build.package_name}/${git_clone.git_tag}
      qiniu_upload_dir: ${git_clone.git_path}/ui/dist
  create_dir:
    type: ssh_cmd:1.0.1
    param:
      ssh_cmd: mkdir -p /home/jianmu-cla
      ssh_ip: 47.243.164.48
      ssh_private_key: ((private_key.alixg))
  update_index_page:
    type: scp_resouce:1.1.0
    param:
      ssh_private_key: ((private_key.alixg))
      ssh_ip: 47.243.164.48
      remote_file: /home/jianmu-cla/index.html
      local_file: ${git_clone.git_path}/ui/dist/index.html
  send_message:
    type: qywx_notice:1.2.1
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_mobile_list: "[]"
      text_content: "建木CLA前端CDN更新完成。\\n\\n版本：${git_clone.git_tag}\\n\\n网址：https://jianmu.opencla.org"
      msgtype: "text"
      mentioned_list: "[]"
