name: 更新ssl证书：*.jianmu.dev

global:
  param:
    domain: "*.jianmu.dev"
    ssl_dir: /etc/nginx/ssl/_.jianmu.dev
    ssl_dir_nexus: /mnt/nginx/cert
    ssl_dir_test_env: /home/ubuntu/ssl/_.jianmu.dev

trigger:
  type: cron
  schedule: 0 0 12 3 * ? *

workflow:
  start:
    type: start
    targets:
      - acme_ssl_aliyun
  acme_ssl_aliyun:
    sources:
      - start
    targets:
      - scp_cert
      - scp_key
      - scp_cert_nexus
      - scp_key_nexus
      - scp_cert_test_env
      - scp_key_test_env
    type: acme_ssl_aliyun:1.0.1
    param:
      wget_use: false
      ali_key: ((ali.jianmu_dev_key))
      domain: ${global.domain}
      ali_secret: ((ali.jianmu_dev_secret))
      dns_check: true
      email: dev@jianmu.dev
  scp_cert:
    sources:
      - acme_ssl_aliyun
    targets:
      - ssh_cmd
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 47.243.164.48
      ssh_private_key: ((private_key.alixg))
      remote_file: ${global.ssl_dir}/fullchain.cer
      local_file: ${acme_ssl_aliyun.cer_path}
  scp_key:
    sources:
      - acme_ssl_aliyun
    targets:
      - ssh_cmd
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 47.243.164.48
      ssh_private_key: ((private_key.alixg))
      remote_file: ${global.ssl_dir}/private.key
      local_file: ${acme_ssl_aliyun.key_path}
  ssh_cmd:
    sources:
      - scp_cert
      - scp_key
    targets:
      - send_message
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 47.243.164.48
      ssh_private_key: ((private_key.alixg))
      ssh_cmd: systemctl restart nginx
  scp_cert_nexus:
    sources:
      - acme_ssl_aliyun
    targets:
      - restart_nexus_nginx
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.20.150.5
      ssh_private_key: ((private_key.nexus))
      remote_file: ${global.ssl_dir_nexus}/fullchain.cer
      local_file: ${acme_ssl_aliyun.cer_path}
  scp_key_nexus:
    sources:
      - acme_ssl_aliyun
    targets:
      - restart_nexus_nginx
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.20.150.5
      ssh_private_key: ((private_key.nexus))
      remote_file: ${global.ssl_dir_nexus}/private.key
      local_file: ${acme_ssl_aliyun.key_path}
  restart_nexus_nginx:
    sources:
      - scp_cert_nexus
      - scp_key_nexus
    targets:
      - send_message
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 172.20.150.5
      ssh_private_key: ((private_key.nexus))
      ssh_cmd: docker restart docker-compose_nginx_1
  scp_cert_test_env:
    sources:
      - acme_ssl_aliyun
    targets:
      - restart_nginx_test_env
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.16.101.253
      ssh_user: ubuntu
      ssh_private_key: ((private_key.jianmu_test))
      remote_file: ${global.ssl_dir_test_env}/fullchain.cer
      local_file: ${acme_ssl_aliyun.cer_path}
  scp_key_test_env:
    sources:
      - acme_ssl_aliyun
    targets:
      - restart_nginx_test_env
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.16.101.253
      ssh_user: ubuntu
      ssh_private_key: ((private_key.jianmu_test))
      remote_file: ${global.ssl_dir_test_env}/private.key
      local_file: ${acme_ssl_aliyun.key_path}
  restart_nginx_test_env:
    sources:
      - scp_cert_test_env
      - scp_key_test_env
    targets:
      - send_message
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 172.16.101.253
      ssh_user: ubuntu
      ssh_private_key: ((private_key.jianmu_test))
      ssh_cmd: sudo systemctl restart nginx
  send_message:
    sources:
      - ssh_cmd
      - restart_nexus_nginx
      - restart_nginx_test_env
    targets:
      - end
    type: qywx_notice:1.2.1
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "更新ssl证书（${global.domain}）更新完成。"
      msgtype: "text"
      mentioned_list: "[]"
  end:
    type: end
    sources:
      - send_message
