name: 建木博客CDN CI/CD
description: 建木博客CDN CI/CD

global:
  param:
    package_name: jianmu-blog
    cdn_base_url: https://cdn.jianmu.run

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: gitee_event
      type: STRING
      exp: $.header.X-Gitee-Event
    - name: gitee_tag_created
      type: BOOL
      exp: $.body.json.created
    - name: gitee_ref
      type: STRING
      exp: $.body.json.ref
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  only: (${trigger.gitee_event} === "Tag Push Hook" && ${trigger.gitee_tag_created})

workflow:
  start:
    type: start
    targets:
      - git_clone
  git_clone:
    type: git_clone:1.2.0
    sources:
      - start
    targets:
      - confirm_root
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-blog.git
      ref: ${trigger.gitee_ref}
  confirm_root:
    image: ubuntu:18.04
    sources:
      - git_clone
    targets:
      - node_build
    environment:
      replacement_cdn: ${global.cdn_base_url}
      replacement_root: /${global.package_name}/${git_clone.git_tag}
      config_file_path: ${git_clone.git_path}/_config.yml
    script:
      - cat ${CONFIG_FILE_PATH}
      - 'sed -i "s|url: https://blog.jianmu.dev|url: ${REPLACEMENT_CDN}${REPLACEMENT_ROOT}|" ${CONFIG_FILE_PATH}'
      - 'sed -i "s|root: /|root: ${REPLACEMENT_ROOT}|" ${CONFIG_FILE_PATH}'
      - cat ${CONFIG_FILE_PATH}
  node_build:
    type: nodejs_build:1.2.1-16.13.0
    sources:
      - confirm_root
    targets:
      - qiniu_upload
      - git_clone_wrapper
    param:
      workspace: ${git_clone.git_path}
      build_arg: --mode prod
  qiniu_upload:
    type: qiniu_upload:1.0.3
    sources:
      - node_build
    targets:
      - send_message
    param:
      qiniu_bucket: jianmu
      qiniu_ak: ((qiniu.AccessKey))
      qiniu_sk: ((qiniu.SecretKey))
      qiniu_zone: z1
      qiniu_upload_uri_prefix: ${global.package_name}/${git_clone.git_tag}
      qiniu_upload_dir: ${git_clone.git_path}/public
  git_clone_wrapper:
    type: git_clone:1.2.0
    sources:
      - node_build
    targets:
      - node_build_wrapper
    param:
      remote_url: https://gitee.com/jianmu-hub/jianmu-cdn-wrapper.git
      ref: refs/heads/master
      username: ((gitee.username))
      password: ((gitee.password))
  node_build_wrapper:
    image: node:14.16.1-alpine3.13
    sources:
      - git_clone_wrapper
    targets:
      - qiniu_upload_wrapper
      - update_index_page
      - update_rss_file
    environment:
      workspace: ${git_clone_wrapper.git_path}
      jianmu_cdn_base_url: ${global.cdn_base_url}
      jianmu_cdn_index_path: /
      jianmu_cdn_upload_uri_prefix: ${global.package_name}/${git_clone.git_tag}
    script:
      - cd ${WORKSPACE}
      - ls -a
      - yarn install
      - yarn build --mode cdn
  qiniu_upload_wrapper:
    type: qiniu_upload:1.0.3
    sources:
      - node_build_wrapper
    targets:
      - send_message
    param:
      qiniu_bucket: jianmu
      qiniu_ak: ((qiniu.AccessKey))
      qiniu_sk: ((qiniu.SecretKey))
      qiniu_zone: z1
      qiniu_upload_uri_prefix: jianmu-cdn-wrapper/${global.package_name}/${git_clone.git_tag}
      qiniu_upload_dir: ${git_clone_wrapper.git_path}/dist
  update_index_page:
    type: scp_resouce:1.1.0
    sources:
      - node_build_wrapper
    targets:
      - send_message
    param:
      ssh_ip: 47.243.164.48
      ssh_private_key: ((private_key.alixg))
      remote_file: /home/jianmu-blog/index.html
      local_file: ${git_clone_wrapper.git_path}/dist/index.html
  update_rss_file:
    type: scp_resouce:1.1.0
    sources:
      - node_build_wrapper
    targets:
      - send_message
    param:
      ssh_ip: 47.243.164.48
      ssh_private_key: ((private_key.alixg))
      remote_file: /home/jianmu-blog/jm.xml
      local_file: ${git_clone.git_path}/public/jm.xml
  send_message:
    type: qywx_notice:1.2.1
    sources:
      - qiniu_upload
      - qiniu_upload_wrapper
      - update_index_page
      - update_rss_file
    targets:
      - end
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_mobile_list: "[]"
      text_content: "建木博客cdn更新完成\\n\\n版本：${git_clone.git_tag}\\n\\n网址：https://blog.jianmu.dev"
      msgtype: "text"
      mentioned_list: "[]"
  end:
    type: end
    sources:
      - send_message
