name: 建木博客测试环境CI/CD
description: 建木博客测试环境CI/CD

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: pr_state
      type: STRING
      exp: $.body.json.pull_request.state
    - name: pr_target_branch
      type: STRING
      exp: $.body.json.target_branch
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  only: (${trigger.pr_target_branch} == "master" && ${trigger.pr_state} == "merged")

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-blog.git
      ref: refs/heads/master
  node_build:
    type: nodejs_build:1.2.1-16.13.0
    param:
      workspace: ${git_clone.git_path}
  update_resoure:
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.16.101.253
      ssh_user: ubuntu
      ssh_private_key: ((private_key.172_16_101_253))
      remote_file: /home/ubuntu/jianmu-blog
      local_file: ${git_clone.git_path}/public
  send_message:
    type: qywx_notice:1.2.1
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木博客测试环境更新完成"
      msgtype: "text"
      mentioned_list: "[]"
