name: 建木博客测试环境CI/CD
description: 建木博客测试环境CI/CD

# 触发器
trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: pr_state
      type: STRING
      exp: $.body.json.pull_request.state
    - name: pr_target_branch
      type: STRING
      exp: $.body.json.target_branch
    auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  # 触发器执行规则，为true时执行流程
  only: (${trigger.pr_target_branch} == "master" && ${trigger.pr_state} == "merged")

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/qbhfh/jianmu-blog.git
      ref: refs/heads/master

  # shell节点
  confirm_root:
    image: ubuntu:18.04
    environment:
      replacement_cdn: https://blog.test.jianmu.dev
      config_file_path: ${git_clone.git_path}/_config.yml
    script:
      - cat ${CONFIG_FILE_PATH}
      - 'sed -i "s|url: https://blog.jianmu.dev|url: ${REPLACEMENT_CDN}|" ${CONFIG_FILE_PATH}'
      - cat ${CONFIG_FILE_PATH}

  # build节点-将克隆的代码进行build
  node_build:
    type: nodejs_build:1.2.1-16.13.0
    param:
      workspace: ${git_clone.git_path}

  # 更新资源-文件替换
  update_resoure:
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.20.148.16
      ssh_user: root
      ssh_private_key: ((private_key.172_20_148_16))
      remote_file: /home/qbhfh/jianmu-blog
      local_file: ${git_clone.git_path}/public

      # 信息通知-企业微信通知
  send_message:
    type: qywx_notice:1.2.1
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_mobile_list: "[]"
      text_content: "建木博客测试环境更新完成\\n\\n版本：${node_build.package_version}\\n\\n网址：https://blog.test.jianmu.dev"
      msgtype: "text"
      mentioned_list: "[]"