name: 建木博客CI/CD
description: 建木博客CI/CD

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-blog.git
      ref: refs/heads/master
  node_build:
    type: nodejs_build:1.2.1-14.16.1
    param:
      workspace: ${git_clone.git_path}
  update_resoure:
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 47.243.164.48
      ssh_private_key: ((private_key.alixg))
      remote_file: /home/jianmu-blog
      local_file: ${git_clone.git_path}/public
#  update_resoure:
#    type: scp_resouce:1.1.0
#    param:
#      ssh_ip: 172.16.101.254
#      ssh_user: ubuntu
#      ssh_private_key: ((private_key.jianmu_prod))
#      remote_file: /home/ubuntu/jianmu-blog
#      local_file: ${git_clone.git_path}/public
  send_message:
    type: qywx_notice:1.2.1
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木博客更新完成"
      msgtype: "text"
      mentioned_list: "[]"
