name: 构建单点登录docker镜像
description: 构建单点登录docker镜像

global:
  param:
    image_name: jianmudev/private
    image_tag_prefix: jianmu-sso
    image_tag_suffix: 1.0.1

pipeline:
  git_clone:
    type: git_clone:1.1.1
    param:
      remote_url: https://gitee.com/letspay/sso.git
      ref: refs/heads/master
  node_build:
    type: nodejs_build:1.2.1-14.16.1
    param:
      workspace: ${git_clone.git_path}
  image_build:
    type: docker_image_build:1.0.1
    param:
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      image_name: ${global.image_name}
      image_tag: ${global.image_tag_prefix}-${global.image_tag_suffix}
      docker_file: Dockerfile
      docker_build_path: .
      workspace: ${git_clone.git_path}