name: 建木单点登录v2测试环境 CI/CD
description: 建木单点登录v2测试环境 CI/CD

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: pr_state
      type: STRING
      exp: $.body.json.pull_request.state
    - name: pr_target_branch
      type: STRING
      exp: $.body.json.target_branch
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  only: (${trigger.pr_target_branch} == "master" && ${trigger.pr_state} == "merged")

global:
  param:
    image_name: jianmudev/private
    image_tag_prefix: jianmu-sso
    image_tag_suffix: v2-latest

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-hub/jianmu-sso.git
      ref: refs/heads/master
      username: ((gitee.username))
      password: ((gitee.password))
  maven_jib_build:
    type: maven_build:1.3.1-jdk11
    param:
      mvn_action: install
      workspace: ${git_clone.git_path}
      image_name: ${global.image_name}
      image_tag: ${global.image_tag_prefix}-${global.image_tag_suffix}
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      maven_public_url: https://nexus.internal.jianmu.dev/repository/maven-public/
      vc_pom_dir: web
  deploy_server:
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 192.168.0.222
      ssh_private_key: ((jianmu_hub.server_private_key))
      ssh_cmd: >-
        docker images
        &&
        docker ps
        &&
        cd /root/jianmu-hub-deploy/sso
        &&
        docker pull ${global.image_name}:${global.image_tag_prefix}-${global.image_tag_suffix}
        &&
        docker-compose -f docker-compose-v2.yml down --rmi all
        &&
        echo v2_version=${global.image_tag_suffix} > .env
        &&
        docker-compose -f docker-compose-v2.yml up -d
        &&
        docker images
        &&
        docker ps
        &&
        echo done
  feishu_notice:
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      app_id: ((feishu.app_id))
      app_secret: ((feishu.app_secret))
      msg_title: 建木单点登录v2测试环境更新完成
      msg_text: "版本：${maven_jib_build.version}\n\n请验收功能。"
      msg_at_phone_list: '["15320260902"]'