name: 建木单点登录v2生产环境 CI/CD
description: 建木单点登录v2生产环境 CI/CD

global:
  param:
    image_name: jianmudev/private
    image_tag_prefix: jianmu-sso

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: gitee_event
      type: STRING
      exp: $.header.X-Gitee-Event
    - name: gitee_tag_created
      type: BOOL
      exp: $.body.json.created
    - name: gitee_ref
      type: STRING
      exp: $.body.json.ref
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  only: (${trigger.gitee_event} === "Tag Push Hook" && ${trigger.gitee_tag_created})

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-hub/jianmu-sso.git
      ref: ${trigger.gitee_ref}
      username: ((gitee.username))
      password: ((gitee.password))
  maven_jib_build:
    type: maven_build:1.3.1-jdk11
    param:
      mvn_action: install
      workspace: ${git_clone.git_path}
      image_name: ${global.image_name}
      image_tag: ${global.image_tag_prefix}-${git_clone.git_tag}
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      maven_public_url: https://nexus.internal.jianmu.dev/repository/maven-public/
      vc_pom_dir: web
  deploy_server:
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 172.16.101.200
      ssh_user: ubuntu
      ssh_private_key: ((private_key.200))
      ssh_cmd: >-
        docker images
        &&
        docker ps
        &&
        cd /home/ubuntu/sso/v2
        &&
        docker pull ${global.image_name}:${global.image_tag_prefix}-${git_clone.git_tag}
        &&
        docker-compose down --rmi all
        &&
        echo v2_version=${git_clone.git_tag} > .env
        &&
        docker-compose up -d
        &&
        docker images
        &&
        docker ps
        &&
        echo done
  feishu_notice:
    type: feishu_notice_interactive:1.0.2
      param:
        bot_webhook_url: ((feishu.webhook_url))
        msg_title: 建木单点登录v2生产环境更新完成
        msg_text: "版本：${git_clone.git_tag}"
  send_email:
    type: email:1.0.0
    param:
      host: smtp.ym.163.com
      sender: notice@jianmu.dev
      auth_code: ((email.notice_auth_code))
      receivers: '["dev@jianmu.dev"]'
      type: html
      subject: 建木单点登录v2生产环境更新完成:${git_clone.git_tag}
      text: 建木单点登录v2生产环境更新完成。<br/>版本：${git_clone.git_tag}