name: 构建API网关docker镜像
description: 构建API网关docker镜像

global:
  param:
    image_name: jianmudev/private

pipeline:
  git_clone:
    type: git_clone:1.0.0
    param:
      remote_url: https://gitee.com/jianmu-hub/jianmu-api-gateway.git
      ref: refs/heads/master
      netrc_username: ((gitee.username))
      netrc_password: ((gitee.password))
      netrc_machine: gitee.com
  node_build:
    type: nodejs_build:1.0.0-14.16.1
    param:
      workspace: ${git_clone.git_path}
  image_build:
    type: docker_image_build:1.0.0
    param:
      workspace: ${git_clone.git_path}
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      docker_file: Dockerfile
      image_name: ${global.image_name}
      image_tag: ${node_build.package_name}-${node_build.package_version}
      docker_build_path: .
  send_message:
    type: qywx_notice:1.0.0
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "API网关docker镜像构建完成。\\n\\n镜像：${global.image_name}:${node_build.package_name}-${node_build.package_version}"
      msgtype: "text"
      mentioned_list: "[]"