name: 构建API网关docker镜像
description: 构建API网关docker镜像

global:
  param:
    image_name: jianmudev/private

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-hub/jianmu-api-gateway.git
      ref: refs/heads/master
      username: ((gitee.username))
      password: ((gitee.password))
  node_build:
    type: nodejs_build:1.2.1-14.16.1
    param:
      workspace: ${git_clone.git_path}
      registry_url: https://registry.npm.taobao.org
  image_build:
    type: docker_image_build:1.0.1
    param:
      workspace: ${git_clone.git_path}
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      docker_file: Dockerfile
      image_name: ${global.image_name}
      image_tag: ${node_build.package_name}-${node_build.package_version}
      docker_build_path: .
  feishu_notice:
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      msg_title: API网关docker镜像构建完成
      msg_text: "镜像：${global.image_name}:${node_build.package_name}-${node_build.package_version}"
  send_email:
    type: email:1.0.0
    param:
      host: smtp.ym.163.com
      sender: notice@jianmu.dev
      auth_code: ((email.notice_auth_code))
      receivers: '["dev@jianmu.dev"]'
      type: html
      subject: API网关docker镜像构建完成:${node_build.package_version}
      text: API网关docker镜像构建完成。<br/>镜像：${global.image_name}:${node_build.package_name}-${node_build.package_version}