name: 建木官网测试环境 CI/CD
description: 建木官网测试环境 CI/CD

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: pr_state
      type: STRING
      exp: $.body.json.pull_request.state
    - name: pr_target_branch
      type: STRING
      exp: $.body.json.target_branch
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  only: (${trigger.pr_target_branch} == "master" && ${trigger.pr_state} == "merged")

pipeline:
  # 从git上面clone前端项目
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-official-site.git
      ref: refs/heads/${trigger.pr_target_branch}
      username: ((gitee.username))
      password: ((gitee.password))
  node_build:
    type: nodejs_build:1.2.1-16.13.0
    param:
      workspace: ${git_clone.git_path}
      registry_url: https://registry.npm.taobao.org
  # 替换远端服务器中的文件资源
  update_resoure:
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.20.150.15
      ssh_user: root
      ssh_private_key: ((private_key.172_20_150_15))
      # 远端服务器存放文件的路径
      remote_file: /home/comyan/jianmu-official-site
      # 本地文件所在的文件路径
      local_file: ${git_clone.git_path}/dist
  feishu_notice:
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      app_id: ((feishu.app_id))
      app_secret: ((feishu.app_secret))
      msg_title: 建木官网测试环境更新完成
      msg_text: "版本：${node_build.package_version}\n\n网址：https://portal.test.jianmu.dev"
      msg_at_phone_list: '["18881035295", "17772427748"]'
  feishu_notice_ui:
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      app_id: ((feishu.app_id))
      app_secret: ((feishu.app_secret))
      msg_title: 建木官网测试环境更新完成
      msg_text: "版本：${node_build.package_version}\n\n网址：https://portal.test.jianmu.dev"
      msg_at_phone_list: '["18201560161", "18810015728"]'
