name: 建木官网CDN CI/CD
description: 建木官网CDN CI/CD

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: gitee_event
      type: STRING
      exp: $.header.X-Gitee-Event
    - name: gitee_tag_created
      type: BOOL
      exp: $.body.json.created
    - name: gitee_ref
      type: STRING
      exp: $.body.json.ref
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  only: (${trigger.gitee_event} === "Tag Push Hook" && ${trigger.gitee_tag_created})

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-official-site.git
      ref: ${trigger.gitee_ref}
      username: ((gitee.username))
      password: ((gitee.password))
  node_build:
    type: nodejs_build:1.2.1-16.13.0
    param:
      workspace: ${git_clone.git_path}
      build_arg: --mode cdn
  qiniu_upload:
    type: qiniu_upload:1.0.3
    param:
      qiniu_bucket: jianmu
      qiniu_ak: ((qiniu.AccessKey))
      qiniu_sk: ((qiniu.SecretKey))
      qiniu_zone: z1
      qiniu_upload_uri_prefix: ${node_build.package_name}/${git_clone.git_tag}
      qiniu_upload_dir: ${git_clone.git_path}/dist
  update_index_page:
    type: scp_resouce:1.1.0
    param:
      ssh_private_key: ((private_key.alixg))
      ssh_ip: 47.243.164.48
      remote_file: /home/jianmu-official-site/index.html
      local_file: ${git_clone.git_path}/dist/index.html
  send_message:
    type: qywx_notice:1.2.1-text
    param:
      bot_webhook_url: ((charbot.webhook_url))
      text_content: "建木官网CDN更新完成\\n\\n版本：${git_clone.git_tag}\\n\\n网址：https://jianmu.dev"
  send_message_ui:
    type: qywx_notice:1.2.1-text
    param:
      bot_webhook_url: ((charbot.ui_webhook_url))
      text_content: "建木官网CDN更新完成\\n\\n版本：${git_clone.git_tag}\\n\\n网址：https://jianmu.dev"
