name: 建木官网CDN CI/CD
description: 建木官网CDN CI/CD

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: gitee_event
      type: STRING
      exp: $.header.X-Gitee-Event
    - name: gitee_tag_created
      type: BOOL
      exp: $.body.json.created
    - name: gitee_ref
      type: STRING
      exp: $.body.json.ref
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  only: (${trigger.gitee_event} === "Tag Push Hook" && ${trigger.gitee_tag_created})

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-official-site.git
      ref: ${trigger.gitee_ref}
      username: ((gitee.username))
      password: ((gitee.password))
  node_build:
    type: nodejs_build:1.2.1-16.13.0
    param:
      workspace: ${git_clone.git_path}
      registry_url: https://registry.npm.taobao.org
      build_arg: --mode cdn
  qiniu_upload:
    type: qiniu:1.0.0-file-upload
    param:
      qiniu_bucket: jianmu
      qiniu_ak: ((qiniu.AccessKey))
      qiniu_sk: ((qiniu.SecretKey))
      qiniu_zone: z1
      qiniu_upload_uri_prefix: ${node_build.package_name}/${git_clone.git_tag}
      qiniu_upload_dir: ${git_clone.git_path}/dist
  update_index_page:
    type: scp_resouce:1.1.0
    param:
      ssh_private_key: ((private_key.alixg))
      ssh_ip: 47.243.164.48
      remote_file: /home/jianmu-official-site/index.html
      local_file: ${git_clone.git_path}/dist/index.html
  feishu_notice:
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      msg_title: 建木官网CDN更新完成
      msg_text: "版本：${git_clone.git_tag}\n\n网址：https://jianmu.dev"
  feishu_notice_ui:
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      msg_title: 建木官网CDN更新完成
      msg_text: "版本：${git_clone.git_tag}\n\n网址：https://jianmu.dev"
  send_email:
    type: email:1.0.0
    param:
      host: smtp.ym.163.com
      sender: notice@jianmu.dev
      auth_code: ((email.notice_auth_code))
      receivers: '["dev@jianmu.dev"]'
      type: html
      subject: 建木官网CDN更新完成:${git_clone.git_tag}
      text: 建木官网CDN更新完成。<br/>版本：${git_clone.git_tag}<br/><br/>网址：https://jianmu.dev
