trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: pr_state
      type: STRING
      exp: $.body.json.pull_request.state
    - name: pr_target_branch
      type: STRING
      exp: $.body.json.target_branch
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  matcher: (${trigger.pr_target_branch} == "web" && ${trigger.pr_state} == "merged")

pipeline:
  name: 建木官网PC端测试环境 CI/CD
  description: 建木官网PC端测试环境 CI/CD
  git_clone:
    type: git_clone:1.1.1
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-official-site.git
      ref: refs/heads/${trigger.pr_target_branch}
      netrc_machine: gitee.com
      netrc_username: ((gitee.username))
      netrc_password: ((gitee.password))
  node_build:
    type: nodejs_build:1.2.0-16.13.0
    param:
      workspace: ${git_clone.git_path}
  update_resoure:
    type: scp_resouce:1.0.0
    param:
      ssh_ip: 47.243.164.48
      ssh_private_key: ((private_key.alixg))
      remote_file: /home/jianmu-official-site/${trigger.pr_target_branch}
      local_file: ${git_clone.git_path}/dist
  send_message:
    type: qywx_notice:1.0.0
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木官网PC端测试环境更新完成\\n\\n版本：${node_build.package_version}"
      msgtype: "text"
      mentioned_mobile_list: '["18881035295", "17772427748"]'
