name: 构建建木CI前/后端docker镜像
description: 构建建木CI前/后端docker镜像

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: gitee_event
      type: STRING
      exp: $.header.X-Gitee-Event
    - name: gitee_tag_created
      type: BOOL
      exp: $.body.json.created
    - name: gitee_ref
      type: STRING
      exp: $.body.json.ref
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  only: (${trigger.gitee_event} === "Tag Push Hook" && ${trigger.gitee_tag_created})

global:
  param:
    ui_image_name: jianmudev/jianmu-ci-ui
    server_image_name: jianmudev/jianmu-ci-server

workflow:
  start:
    type: start
    targets:
      - git_clone
  git_clone:
    type: git_clone:1.2.0
    sources:
      - start
    targets:
      - maven_jib_build
      - node_build
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-ci-server.git
      ref: ${trigger.gitee_ref}
      username: ((gitee.username))
      password: ((gitee.password))
  maven_jib_build:
    type: maven_build:1.3.1-jdk11
    sources:
      - git_clone
    targets:
      - send_message
    param:
      mvn_action: install
      workspace: ${git_clone.git_path}
      image_name: ${global.server_image_name}
      image_tag: ${git_clone.git_tag}
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      maven_public_url: https://nexus.internal.jianmu.dev/repository/maven-public/
  node_build:
    type: nodejs_build:1.2.1-14.16.1
    sources:
      - git_clone
    targets:
      - image_build
    param:
      workspace: ${git_clone.git_path}/ui
      registry_url: https://registry.npm.taobao.org
  image_build:
    type: docker_image_build:1.0.1
    sources:
      - node_build
    targets:
      - send_message
    param:
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      image_name: ${global.ui_image_name}
      image_tag: ${git_clone.git_tag}
      docker_file: Dockerfile
      docker_build_path: .
      workspace: ${git_clone.git_path}/ui
  send_message:
    type: feishu_notice_interactive:1.0.2
    sources:
      - maven_jib_build
      - image_build
    targets:
      - send_email
    param:
      bot_webhook_url: ((feishu.webhook_url))
      msg_title: 建木CI前/后端docker镜像构建完成
      msg_text: "前端：${global.ui_image_name}:${git_clone.git_tag}\n后端：${global.server_image_name}:${git_clone.git_tag}"
  send_email:
    sources:
      - send_message
    targets:
      - end
    type: email:1.0.0
    param:
      host: smtp.ym.163.com
      sender: notice@jianmu.dev
      auth_code: ((email.notice_auth_code))
      receivers: '["dev@jianmu.dev"]'
      type: html
      subject: 建木CI前/后端docker镜像构建完成:${git_clone.git_tag}
      text: 建木CI前/后端docker镜像构建完成。<br/>前端：${global.ui_image_name}:${git_clone.git_tag}<br/>后端：${global.server_image_name}:${git_clone.git_tag}
  end:
    type: end
    sources:
      - send_email