# 部署生产，通过上游打镜像流程，触发（结合chat-ops）
name: 建木CI服务端生产环境CD
description: 建木CI服务端生产环境CD

global:
  param:
    image_name: jianmudev/jianmu-ci-server
    image_tag: v2.0.0

pipeline:
  deploy_server:
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 192.168.20.16
      ssh_private_key: ((private_key.ciserver))
      ssh_cmd: >-
        docker images
        &&
        docker ps
        &&
        cd /root/jianmu-ci
        &&
        source ./.env
        &&
        echo source version: $ci_server_version
        &&
        echo target version: ${global.image_tag}
        &&
        docker-compose stop ci-server
        &&
        docker-compose rm -vf ci-server
        &&
        docker rmi ${global.image_name}:$ci_server_version
        &&
        cp .env .env.$(date +'%Y-%m-%d_%H:%M:%S')
        &&
        sed -i '/^ci_server_version=/d' .env
        &&
        echo ci_server_version=${global.image_tag} >> .env
        &&
        docker-compose up -d ci-server
        &&
        docker images
        &&
        docker ps
        &&
        echo done
  send_message:
    type: qywx_notice:1.2.1
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木CI服务端生产环境更新完成。\\n\\n版本：${global.image_tag}"
      msgtype: "text"
      mentioned_list: "[]"