# 部署生产，通过上游打镜像流程，触发（结合chat-ops）
name: 建木CI服务端生产环境CD
description: 建木CI服务端生产环境CD

global:
  param:
    image_name: jianmudev/jianmu-ci-server
    image_tag: v2.2.4

pipeline:
  deploy_server:
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 172.16.101.210
      ssh_user: ubuntu
      ssh_private_key: ((private_key.210))
      ssh_cmd: >-
        docker images
        &&
        docker ps
        &&
        cd /home/ubuntu/ci
        &&
        source ./.env
        &&
        echo source version: $ci_server_version
        &&
        echo target version: ${global.image_tag}
        &&
        docker-compose stop ci-server
        &&
        docker-compose rm -vf ci-server
        &&
        docker rmi ${global.image_name}:$ci_server_version
        &&
        cp .env .env.$(date +'%Y-%m-%d_%H:%M:%S')
        &&
        sed -i '/^ci_server_version=/d' .env
        &&
        echo ci_server_version=${global.image_tag} >> .env
        &&
        docker-compose up -d ci-server
        &&
        docker images
        &&
        docker ps
        &&
        echo done
  feishu_notice:
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      msg_title: 建木CI服务端生产环境更新完成
      msg_text: "版本：${global.image_tag}\n\n网址：https://ci.jianmu.dev"
  send_email:
    type: email:1.0.0
    param:
      host: smtp.ym.163.com
      sender: notice@jianmu.dev
      auth_code: ((email.notice_auth_code))
      receivers: '["dev@jianmu.dev"]'
      type: html
      subject: 建木CI服务端生产环境更新完成:${global.image_tag}
      text: 建木CI服务端生产环境更新完成。<br/>版本：${global.image_tag}<br/><br/>网址：https://ci.jianmu.dev