name: 建木CI前端测试环境 CI/CD
description: 建木CI前端测试环境 CI/CD

global:
  param:
    image_name: jianmudev/jianmu-ci-ui

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: pr_state
      type: STRING
      exp: $.body.json.pull_request.state
    - name: pr_target_branch
      type: STRING
      exp: $.body.json.target_branch
    - name: pr_label
      type: STRING
      exp: $.body.json.pull_request.head.label
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  only: (${trigger.pr_target_branch} == "master" && ${trigger.pr_state} == "merged" && (${trigger.pr_label} == "老技:master" || ${trigger.pr_label} == "冯浩:master" || ${trigger.pr_label} == "comyan:master"))

pipeline:
  git_clone_ui:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-ci-server.git
      ref: refs/heads/master
  node_build:
    type: nodejs_build:1.2.1-14.16.1
    param:
      workspace: ${git_clone_ui.git_path}/ui
  image_build:
    type: docker_image_build:1.0.1
    param:
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      image_name: ${global.image_name}
      image_tag: ${git_clone_ui.git_branch}
      docker_file: Dockerfile
      docker_build_path: .
      workspace: ${git_clone_ui.git_path}/ui
  ssh_cmd:
    type: ssh_cmd:1.0.1
    param:
      ssh_ip: 172.20.148.86
      ssh_private_key: ((jianmu_ci.server_private_key))
      ssh_cmd: >-
        docker images
        &&
        docker ps
        &&
        cd /root/jianmu-ci
        &&
        source ./.env
        &&
        echo source version: $web_version
        &&
        echo target version: ${git_clone_ui.git_branch}
        &&
        docker-compose stop web
        &&
        docker-compose rm -vf web
        &&
        docker rmi ${global.image_name}:$web_version
        &&
        cp .env .env.$(date +'%Y-%m-%d_%H:%M:%S')
        &&
        sed -i '/^web_version=/d' .env
        &&
        echo web_version=${git_clone_ui.git_branch} >> .env
        &&
        docker-compose up -d web
        &&
        docker images
        &&
        docker ps
        &&
        echo done
  send_message:
    type: qywx_notice:1.2.1
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木CI前端测试环境更新完成。\\n\\n开发分支：${git_clone_ui.git_branch}\\n版本：${node_build.package_version}"
      msgtype: "text"
      mentioned_list: "[]"
