pipeline:
  name: 建木CI前端CDN CI/CD
  ref: jianmu_ci_ui_cdn_cicd
  description: 建木CI前端CDN CI/CD
  git_clone:
    type: git_clone:1.0.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-ci-ui.git
      ref: refs/heads/master
  node_build:
    type: nodejs_build:1.0.0-14.16.1
    param:
      workspace: ${git_clone.git_path}
      build_arg: --mode cdn
  qiniu_upload:
    type: qiniu_upload:1.0.1
    param:
      qiniu_bucket: jianmu
      qiniu_ak: ((qiniu.AccessKey))
      qiniu_sk: ((qiniu.SecretKey))
      qiniu_zone: z1
      qiniu_upload_uri_prefix: ${node_build.package_name}/v${node_build.package_version}
      qiniu_upload_dir: ${git_clone.git_path}/dist
  create_dir:
    type: ssh_cmd:1.0.0
    param:
      ssh_cmd: mkdir -p /home/jianmu-ci-ui
      ssh_ip: 8.140.50.113
      ssh_private_key: ((private_key.aliserver))
  update_index_page:
    type: scp_resouce:1.0.0
    param:
      ssh_private_key: ((private_key.aliserver))
      ssh_ip: 8.140.50.113
      remote_file: /home/jianmu-ci-ui/index.html
      local_file: ${git_clone.git_path}/dist/index.html
  send_message:
    type: qywx_notice:1.0.0
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木CI前端CDN更新完成。\\n\\n版本：v${node_build.package_version}"
      msgtype: "text"
      mentioned_list: "[]"
