eb: jianmu_ci_ui_docker_image_hook

param:
  image_name: jianmudev/jianmu-ci-ui
  image_latest_tag: latest

pipeline:
  name: 构建建木CI前端docker镜像
  ref: jianmu_ci_ui_image_builder
  description: 构建建木CI前端docker镜像
  git_clone_ui:
    type: git_clone:1.0.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-ci-ui.git
      ref: ${event.gitee_ref}
  node_build:
    type: nodejs_build:1.0.0-14.16.1
    param:
      workspace: ${git_clone_ui.git_path}
  git_clone_image:
    type: git_clone:1.0.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-ui-image.git
      ref: refs/heads/master
  image_build:
    type: docker_image_build:1.0.0
    param:
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      image_name: ${global.image_name}
      image_tag: ${git_clone_ui.git_tag}
      docker_file: Dockerfile
      docker_build_path: .
      workspace: ${git_clone_image.git_path}
      cmd_pre: cp -r ${git_clone_ui.git_path}/dist .
  image_build_latest:
    type: docker_image_build:1.0.0
    param:
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      image_name: ${global.image_name}
      image_tag: ${global.image_latest_tag}
      docker_file: Dockerfile
      docker_build_path: .
      workspace: ${git_clone_image.git_path}
      cmd_pre: cp -r ${git_clone_ui.git_path}/dist .
  send_message:
    type: qywx_notice:1.0.0
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木CI前端docker镜像构建完成。\\n\\n镜像：\\n${global.image_name}:${git_clone_ui.git_tag}\\n${global.image_name}:${global.image_latest_tag}"
      msgtype: "text"
      mentioned_list: "[]"