#eb: ci_ui_test_ci_cd_hook

param:
  image_name: jianmudev/jianmu-ci-ui

pipeline:
  name: 建木CI前端测试环境 CI/CD
  description: 建木CI前端测试环境 CI/CD
  git_clone_ui:
    type: git_clone:1.0.1
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-ci-server.git
      # TODO 后续来源为event，筛选指定分支的push
      ref: refs/heads/2.0.0
  node_build:
    type: nodejs_build:1.0.0-14.16.1
    param:
      workspace: ${git_clone_ui.git_path}/ui
  git_clone_image:
    type: git_clone:1.0.1
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-ui-image.git
      ref: refs/heads/master
  image_build:
    type: docker_image_build:1.0.0
    param:
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      image_name: ${global.image_name}
      image_tag: ${git_clone_ui.git_branch}
      docker_file: Dockerfile
      docker_build_path: .
      workspace: ${git_clone_image.git_path}
      cmd_pre: cp -r ${git_clone_ui.git_path}/ui/dist .
  ssh_cmd:
    type: ssh_cmd:1.0.0
    param:
      ssh_ip: 172.20.148.86
      ssh_private_key: ((jianmu_ci.server_private_key))
      ssh_cmd: >-
        docker images
        &&
        docker ps
        &&
        cd /root/jianmu-ci
        &&
        source ./.env
        &&
        echo source version: $web_version
        &&
        echo target version: ${git_clone_ui.git_branch}
        &&
        docker-compose stop web
        &&
        docker-compose rm -vf web
        &&
        docker rmi ${global.image_name}:$web_version
        &&
        cp .env .env.$(date +'%Y-%m-%d_%H:%M:%S')
        &&
        sed -i '/^web_version=/d' .env
        &&
        echo web_version=${git_clone_ui.git_branch} >> .env
        &&
        docker-compose up -d web
        &&
        docker images
        &&
        docker ps
        &&
        echo done
  send_message:
    type: qywx_notice:1.0.0
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木CI前端测试环境更新完成。\\n\\n开发分支：${git_clone_ui.git_branch}"
      msgtype: "text"
      mentioned_list: "[]"
