name: 建木CI前端CDN CD 2.2.0-hotfix.1
description: 建木CI前端CDN CD 2.2.0-hotfix.1

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/liamjung/jianmu-ci-server.git
      ref: refs/heads/2.2.0-hotfix.1
      username: ((gitee_lj.username))
      password: ((gitee_lj.password))
  node_build:
    type: nodejs_build:1.2.1-14.16.1
    param:
      workspace: ${git_clone.git_path}/ui
      registry_url: https://registry.npm.taobao.org
      build_arg: --mode cdn
  qiniu_upload:
    type: qiniu:1.0.0-file-upload
    param:
      qiniu_bucket: jianmu
      qiniu_ak: ((qiniu.AccessKey))
      qiniu_sk: ((qiniu.SecretKey))
      qiniu_zone: z1
      qiniu_upload_uri_prefix: ${node_build.package_name}/2.2.0-hotfix.1
      qiniu_upload_dir: ${git_clone.git_path}/ui/dist
  create_dir:
    type: ssh_cmd:1.0.1
    param:
      ssh_cmd: mkdir -p /home/jianmu-ci-ui
      ssh_ip: 47.243.164.48
      ssh_private_key: ((private_key.alixg))
  update_index_page:
    type: scp_resouce:1.1.0
    param:
      ssh_private_key: ((private_key.alixg))
      ssh_ip: 47.243.164.48
      remote_file: /home/jianmu-ci-ui/index.html
      local_file: ${git_clone.git_path}/ui/dist/index.html
