pipeline:
  name: 建木文档CI/CD
  ref: jianmu_docs_cicd
  description: 建木文档CI/CD
  git_clone:
    type: git_clone:1.0.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-docs.git
      ref: refs/heads/master
  node_build:
    type: nodejs_build:1.0.0-14.16.1
    param:
      workspace: ${git_clone.git_path}
  update_resoure:
    type: scp_resouce:1.0.0
    param:
      ssh_ip: 47.243.164.48
      ssh_private_key: ((private_key.alixg))
      remote_file: /etc/nginx/docs
      local_file: ${git_clone.git_path}/.vitepress/dist
  send_message:
    type: qywx_notice:1.0.0
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木文档更新完成"
      msgtype: "text"
      mentioned_list: "[]"
