name: 建木文档v1 CI/CD
description: 建木文档v1 CI/CD

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-docs.git
      ref: refs/heads/v1
  node_build:
    type: nodejs_build:1.2.1-14.16.1
    param:
      workspace: ${git_clone.git_path}
      registry_url: https://registry.npm.taobao.org
  update_resoure:
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 47.243.164.48
      ssh_private_key: ((private_key.alixg))
      remote_file: /home/jianmu-docs/v1
      local_file: ${git_clone.git_path}/.vitepress/dist
  feishu_notice:
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      msg_title: 建木文档v1更新完成
      msg_text: ""
  send_email:
    type: email:1.0.0
    param:
      host: smtp.ym.163.com
      sender: notice@jianmu.dev
      auth_code: ((email.notice_auth_code))
      receivers: '["dev@jianmu.dev"]'
      type: html
      subject: 建木文档v1更新完成
      text: 建木文档v1更新完成