name: 建木文档v2 CI/CD
description: 建木文档v2 CI/CD

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-dev/jianmu-docs.git
      ref: refs/heads/master
  node_build:
    type: nodejs_build:1.2.1-14.16.1
    param:
      workspace: ${git_clone.git_path}
      registry_url: https://registry.npm.taobao.org
  update_resoure:
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 47.243.164.48
      ssh_private_key: ((private_key.alixg))
      remote_file: /home/jianmu-docs/v2
      local_file: ${git_clone.git_path}/.vitepress/dist
  send_message:
    type: qywx_notice:1.2.1
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_mobile_list: "[]"
      text_content: "建木文档v2更新完成"
      msgtype: "text"
      mentioned_list: "[]"
