name: 建木Hub服务端测试环境 CI/CD
description: 建木Hub服务端测试环境 CI/CD

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: pr_state
      type: STRING
      exp: $.body.json.pull_request.state
    - name: pr_target_branch
      type: STRING
      exp: $.body.json.target_branch
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  only: (${trigger.pr_target_branch} == "master" && ${trigger.pr_state} == "merged")

global:
  param:
    image_name: jianmudev/private
    image_tag_prefix: jianmu-hub-server
    image_tag_suffix: latest

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-hub/jianmu-hub-server.git
      ref: refs/heads/master
      username: ((gitee.username))
      password: ((gitee.password))
  maven_jib_build:
    type: maven_build:1.2.0-jdk11
    param:
      mvn_action: install
      workspace: ${git_clone.git_path}
      image_name: ${global.image_name}
      image_tag: ${global.image_tag_prefix}-${global.image_tag_suffix}
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      maven_public_url: https://nexus.internal.jianmu.dev/repository/maven-public/
      vc_pom_dir: web
  deploy_server:
    type: ssh_cmd:1.0.0
    param:
      ssh_ip: 172.20.151.88
      ssh_private_key: ((jianmu_hub.server_private_key))
      ssh_cmd: >-
        docker images
        &&
        docker ps
        &&
        cd /root/jianmu-hub-deploy/hub-server
        &&
        docker pull ${global.image_name}:${global.image_tag_prefix}-${global.image_tag_suffix}
        &&
        docker-compose down --rmi all
        &&
        echo version=${global.image_tag_suffix} > .env
        &&
        docker-compose up -d
        &&
        docker images
        &&
        docker ps
        &&
        echo done
  send_message:
    type: qywx_notice:1.1.0
    param:
      bot_webhook_url: ((charbot.webhook_url))
      text_content: "建木Hub服务端测试环境更新完成。\\n\\n版本：${maven_jib_build.version}\\n\\n网址：https://hub.test.jianmu.dev\\n\\n请验收功能。"
      msgtype: "text"
      mentioned_mobile_list: '["15223806815", "15320260902"]'