eb: hub_server_prod_cicd_hook

global:
  param:
    image_name: jianmudev/private
    image_tag_prefix: jianmu-hub-server

pipeline:
  name: 建木Hub服务端生产环境 CI/CD
  ref: jianmu_hub_server_prod_cicd
  description: 建木Hub服务端生产环境 CI/CD
  git_clone:
    type: git_clone:1.0.0
    param:
      remote_url: https://gitee.com/jianmu-hub/jianmu-hub-server.git
      ref: ${event.gitee_ref}
      netrc_machine: gitee.com
      netrc_username: ((gitee.username))
      netrc_password: ((gitee.password))
  maven_jib_build:
    type: maven_build:1.2.0-jdk11
    param:
      mvn_action: install
      workspace: ${git_clone.git_path}
      image_name: ${global.image_name}
      image_tag: ${global.image_tag_prefix}-${git_clone.git_tag}
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      maven_public_url: https://nexus.jianmu.dev/repository/maven-public/
      vc_pom_dir: web
  deploy_server:
    type: ssh_cmd:1.0.0
    param:
      ssh_ip: 8.140.50.113
      ssh_private_key: ((private_key.aliserver))
      ssh_cmd: >-
        docker images
        &&
        docker ps
        &&
        cd /root/jianmu-hub-deploy/hub-server
        &&
        docker pull ${global.image_name}:${global.image_tag_prefix}-${git_clone.git_tag}
        &&
        docker-compose down --rmi all
        &&
        echo version=${git_clone.git_tag} > .env
        &&
        docker-compose up -d
        &&
        docker images
        &&
        docker ps
        &&
        echo done
  send_message:
    type: qywx_notice:1.0.0
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木Hub服务端生产环境更新完成。\\n\\n镜像：${global.image_name}:${global.image_tag_prefix}-${git_clone.git_tag}"
      msgtype: "text"
      mentioned_list: "[]"