eb: jianmu_hub_ui_cdn_ci_cd_hook

name: 建木Hub前端CDN CI/CD
description: 建木Hub前端CDN CI/CD

pipeline:
  git_clone:
    type: git_clone:1.0.0
    param:
      remote_url: https://gitee.com/jianmu-hub/jianmu-hub-ui.git
      ref: ${event.gitee_ref}
      netrc_machine: gitee.com
      netrc_username: ((gitee.username))
      netrc_password: ((gitee.password))
  node_build:
    type: nodejs_build:1.0.0-14.16.1
    param:
      workspace: ${git_clone.git_path}
      build_arg: --mode cdn
  qiniu_upload:
    type: qiniu_upload:1.0.2
    param:
      qiniu_bucket: jianmu
      qiniu_ak: ((qiniu.AccessKey))
      qiniu_sk: ((qiniu.SecretKey))
      qiniu_zone: z1
      qiniu_upload_uri_prefix: ${node_build.package_name}/${node_build.package_version}
      qiniu_upload_dir: ${git_clone.git_path}/dist
  create_dir:
    type: ssh_cmd:1.0.0
    param:
      ssh_cmd: mkdir -p /home/jianmu-hub-ui
      ssh_ip: 8.140.50.113
      ssh_private_key: ((private_key.aliserver))
  update_index_page:
    type: scp_resouce:1.0.0
    param:
      ssh_private_key: ((private_key.aliserver))
      ssh_ip: 8.140.50.113
      remote_file: /home/jianmu-hub-ui/index.html
      local_file: ${git_clone.git_path}/dist/index.html
  send_message:
    type: qywx_notice:1.0.0
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木Hub前端CDN更新完成。\\n\\n版本：${node_build.package_version}"
      msgtype: "text"
      mentioned_list: "[]"
