name: 建木Hub前端CDN CI/CD
description: 建木Hub前端CDN CI/CD

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: gitee_event
      type: STRING
      exp: $.header.X-Gitee-Event
    - name: gitee_tag_created
      type: BOOL
      exp: $.body.json.created
    - name: gitee_ref
      type: STRING
      exp: $.body.json.ref
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  only: (${trigger.gitee_event} === "Tag Push Hook" && ${trigger.gitee_tag_created})

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-hub/jianmu-hub-ui.git
      ref: ${trigger.gitee_ref}
      username: ((gitee.username))
      password: ((gitee.password))
  node_build:
    type: nodejs_build:1.2.1-14.16.1
    param:
      workspace: ${git_clone.git_path}
      build_arg: --mode cdn
  qiniu_upload:
    type: qiniu_upload:1.0.3
    param:
      qiniu_bucket: jianmu
      qiniu_ak: ((qiniu.AccessKey))
      qiniu_sk: ((qiniu.SecretKey))
      qiniu_zone: z1
      qiniu_upload_uri_prefix: ${node_build.package_name}/${node_build.package_version}
      qiniu_upload_dir: ${git_clone.git_path}/dist
  create_dir:
    type: ssh_cmd:1.0.1
    param:
      ssh_cmd: mkdir -p /home/ubuntu/jianmu-hub-ui
      ssh_ip: 172.16.101.254
      ssh_user: ubuntu
      ssh_private_key: ((private_key.254))
  update_index_page:
    type: scp_resouce:1.1.0
    param:
      ssh_ip: 172.16.101.254
      ssh_user: ubuntu
      ssh_private_key: ((private_key.254))
      remote_file: /home/ubuntu/jianmu-hub-ui/index.html
      local_file: ${git_clone.git_path}/dist/index.html
  send_message:
    type: qywx_notice:1.2.1
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_mobile_list: "[]"
      text_content: "建木Hub前端CDN更新完成。\\n\\n版本：${git_clone.git_tag}\\n\\n网址：https://hub.jianmu.dev"
      msgtype: "text"
      mentioned_list: "[]"
