name: 建木Hub前端测试环境 CI/CD
description: 建木Hub前端测试环境 CI/CD

trigger:
  type: webhook
  param:
    - name: gitee_token
      type: SECRET
      exp: $.header.X-Gitee-Token
    - name: pr_state
      type: STRING
      exp: $.body.json.pull_request.state
    - name: pr_target_branch
      type: STRING
      exp: $.body.json.target_branch
  auth:
    token: ${trigger.gitee_token}
    value: ((gitee.webhook_token))
  only: (${trigger.pr_target_branch} == "master" && ${trigger.pr_state} == "merged")

pipeline:
  git_clone:
    type: git_clone:1.2.0
    param:
      remote_url: https://gitee.com/jianmu-hub/jianmu-hub-ui.git
      ref: refs/heads/master
      username: ((gitee.username))
      password: ((gitee.password))
  node_build:
    type: nodejs_build:1.0.0-14.16.1
    param:
      workspace: ${git_clone.git_path}
      build_arg: --mode test
  #  create_dir:
  #    type: ssh_cmd:1.0.0
  #    param:
  #      ssh_cmd: mkdir -p /home/jianmu-hub-ui
  #      ssh_ip: 192.168.0.222
  #      ssh_private_key: ((jianmu_hub.server_private_key))
  update_resouce:
    type: scp_resouce:1.0.0
    param:
      ssh_ip: 192.168.0.222
      ssh_private_key: ((jianmu_hub.server_private_key))
      remote_file: /home/jianmu-hub-ui
      local_file: ${git_clone.git_path}/dist
  feishu_notice:
    type: feishu_notice_interactive:1.0.2
    param:
      bot_webhook_url: ((feishu.webhook_url))
      app_id: ((feishu.app_id))
      app_secret: ((feishu.app_secret))
      msg_title: 建木Hub前端测试环境更新完成
      msg_text: "版本：${node_build.package_version}\n\n网址：https://hub.test.jianmu.dev\n\n请验收功能。"
      msg_at_phone_list: '["18881035295", "17772427748"]'
